### ISSUE TITLE
Opening app store with no internet connectivity causes a lot of noise in the log

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#1101]
```
request to http://registry.npmjs.org/-/v1/search?size=250&text=keywords:signalk-node-server-plugin failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
FetchError: request to http://registry.npmjs.org/-/v1/search?size=250&text=keywords:signalk-node-server-plugin failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/signalk-server/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
GET /appstore/available 500 16.860 ms - 101
(node:927) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/usr/local/lib/node_modules/signalk-server/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/local/lib/node_modules/signalk-server/node_modules/express/lib/response.js:170:12)
    at findPluginsAndWebapps.then.catch.error (/usr/local/lib/node_modules/signalk-server/lib/interfaces/appstore.js:92:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:927) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:927) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bkeepers** [comment]
This is no longer an issue an can be closed. I just tested it against master and this is the only entry in the log: 

```
request to https://registry.npmjs.org/-/v1/search?size=250&from=0&text=keywords:signalk-node-server-plugin failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org
