### ISSUE TITLE
Log filling with PGN read errors

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1153]
My Signal K log is filling with the following error messages, approx 1 per 30s or so.

I am guessing that my bus includes a PGN that canboatjs can't parse (or maybe not).

Question is: is the verbosity of log output for this type of problem appropriate? Line 2/3 in the log snippet below suggests that the error is in any case being generated in a peculiarly unhelpful way since it doesn't give a place to look for the problem.

I'm happy to help tracking this down or to provide more data.

P

```
DLE followed by unexpected char , ignore message
Oct 12 18:26:02 helm signalk-server[29979]: {}
Oct 12 18:26:02 helm signalk-server[29979]: Error: error reading pgn {} Error: Trying to read past the end of the stream
Oct 12 18:26:02 helm signalk-server[29979]:     at Parser.parseBuffer (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:376:19)
Oct 12 18:26:02 helm signalk-server[29979]:     at Parser.parse (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:245:19)
Oct 12 18:26:02 helm signalk-server[29979]:     at CanboatJs._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/canboatjs.js:49:34)
Oct 12 18:26:02 helm signalk-server[29979]:     at CanboatJs.Transform._read (_stream_transform.js:190:10)
Oct 12 18:26:02 helm signalk-server[29979]:     at CanboatJs.Transform._write (_stream_transform.js:178:12)
Oct 12 18:26:02 helm signalk-server[29979]:     at doWrite (_stream_writable.js:415:12)
Oct 12 18:26:02 helm signalk-server[29979]:     at writeOrBuffer (_stream_writable.js:399:5)
Oct 12 18:26:02 helm signalk-server[29979]:     at CanboatJs.Writable.write (_stream_writable.js:299:11)
Oct 12 18:26:02 helm signalk-server[29979]:     at SerialStream.ondata (_stream_readable.js:710:20)
Oct 12 18:26:02 helm signalk-server[29979]:     at SerialStream.emit (events.js:198:13)
Oct 12 18:26:02 helm signalk-server[29979]:     at addChunk (_stream_readable.js:288:12)
Oct 12 18:26:02 helm signalk-server[29979]:     at readableAddChunk (_stream_readable.js:269:11)
Oct 12 18:26:02 helm signalk-server[29979]:     at SerialStream.Readable.push (_stream_readable.js:224:10)
Oct 12 18:26:02 helm signalk-server[29979]:     at SerialStream.Transform.push (_stream_transform.js:151:32)
Oct 12 18:26:02 helm signalk-server[29979]:     at processN2KMessage (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/serial.js:408:10)
Oct 12 18:26:02 helm signalk-server[29979]:     at read1Byte (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/serial.js:235:11)
Oct 12 18:26:46 helm signalk-server[29979]: DLE followed by unexpected char , ignore message
```

**Comment by dirkwa** [comment]
Hi, 

do you still have this with a fresh nodeJS16 based Version 1.41.3 ?

For me a PGN can not be mapped.
 CanboatJS - Undefined PGN 60928 #1423

**Comment by dirkwa** [comment]
@tkurki 

I would recommend to close this stale issue.

1. no interaction since >5yrs
2. codebase massively changed
3. Correct place would be [canboatjs](https://github.com/canboat/canboatjs/issues) anyway.
