### ISSUE TITLE
Crash at start of signalk-server

### ISSUE THREAD

**Issue by dkroeske** [SignalK/signalk-server#1317]
Unable to start signalk-server, on headless mini pc running Ubuntu 20.04.

npm install reports:

`npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'signalk-server@1.39.0',
npm WARN EBADENGINE   required: { node: '^10' },
npm WARN EBADENGINE   current: { node: 'v13.6.0', npm: '7.11.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'nanoid@3.1.22',
npm WARN EBADENGINE   required: { node: '^10 || ^12 || ^13.7 || ^14 || >=15.0.1' },
npm WARN EBADENGINE   current: { node: 'v13.6.0', npm: '7.11.2' }
`
can't start signalk-server. It crashes with:

`export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
`
Any idea?

regards, Diederich (and have a nice day)

**Comment by tkurki** [comment]
You have node version v13.6.0, and apparently the server is not compatible with that. We are officially still on version 10, but the server is known to work on 12 and 14. I suggest you upgrade to 14, but you need to reinstall the server after node.
