### ISSUE TITLE
Handle npm timeouts gracefully

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#1420]
Failing npm registry fetches are not handled and will cause a server process restart via unhandled promise rejection.

https://github.com/SignalK/signalk-server/issues/1419#issuecomment-1068346601

We need to indicate to the admin ui that the app store is not available, just returning an empty result will look like the app store is not working.

**Comment by tkurki** [comment]
Causes also stacktraces in the log for people to wonder about and report.

**Comment by tkurki** [comment]
```
request to http://registry.npmjs.org/-/v1/search?size=250&text=keywords:signalk-node-server-plugin failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org
FetchError: request to http://registry.npmjs.org/-/v1/search?size=250&text=keywords:signalk-node-server-plugin failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org
    at ClientRequest.<anonymous> (/Users/teppokurki/git-workspace/signalk/server/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:394:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
GET /skServer/appstore/available 500 22.391 ms - 321
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:370:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at ServerResponse.header (/Users/teppokurki/git-workspace/signalk/server/node_modules/express/lib/response.js:776:10)
    at ServerResponse.send (/Users/teppokurki/git-workspace/signalk/server/node_modules/express/lib/response.js:170:12)
    at /Users/teppokurki/git-workspace/signalk/server/lib/interfaces/appstore.js:129:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by bkeepers** [comment]
Duplicate of https://github.com/SignalK/signalk-server/issues/1101 and can also be closed.
