### ISSUE TITLE
RMC Sentence is invalid at Parser

### ISSUE THREAD

**Issue by cedschmidt-lab** [SignalK/signalk-server#1427]
Hello everyone,

I installed a new GPS sending RMC sentence via UDP and just remarked the following error occurring on about 1 packet over 3. Can someone help me with this?? I tried to check the checksum but seems okay... No idea where to look at.

Thanks for your help

`Mar 29 15:49:08 2022-03-29T14:49:08.445Z signalk:streams:nmea0183-signalk Error: Sentence "$GPRMC,120738.50,A,4518.253171,N,00310.861253,E,3.254,239.42,280321,2.00,E,F,S*42" is invalid at Parser.parse (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@signalk\nmea0183-signalk\lib\index.js:78:13) at Nmea0183ToSignalK._transform (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@signalk\streams\nmea0183-signalk.js:99:29) at Nmea0183ToSignalK.Transform._write (node:internal/streams/transform:184:23) at writeOrBuffer (node:internal/streams/writable:389:12) at _write (node:internal/streams/writable:330:10) at Nmea0183ToSignalK.Writable.write (node:internal/streams/writable:334:10) at Replacer.ondata (node:internal/streams/readable:754:22) at Replacer.emit (node:events:390:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Replacer.Readable.push (node:internal/streams/readable:228:10) at Replacer._transform (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@signalk\streams\replacer.js:31:8) at Replacer.Transform._write (node:internal/streams/transform:184:23) at writeOrBuffer (node:internal/streams/writable:389:12) at _write (node:internal/streams/writable:330:10) at Replacer.Writable.write (node:internal/streams/writable:334:10)`

**Comment by cedschmidt-lab** [comment]
Thanks a lot tkurki! Will check the device...
