### ISSUE TITLE
Cors failure logs too much

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#1576]
```
Jul 11 17:31:16 Error: http://localhost:3002 not allowed at corsOptions.origin (/usr/lib/node_modules/signalk-server/lib/cors.js:42:20) at /usr/lib/node_modules/signalk-server/node_modules/cors/lib/index.js:219:13 at optionsCallback (/usr/lib/node_modules/signalk-server/node_modules/cors/lib/index.js:199:9) at corsMiddleware (/usr/lib/node_modules/signalk-server/node_modules/cors/lib/index.js:204:7) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:328:13) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:286:9 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:91:12) at trim_prefix (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:328:13) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:286:9 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at logger (/usr/lib/node_modules/signalk-server/node_modules/morgan/index.js:144:5) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by JacoKoster** [comment]
I have been looking into how cors is handled in the server and it looks like changes in the allowedCorsOrigins need a restart of the server to be effective. Is that correct?

**Comment by JacoKoster** [comment]
Just checked on slack: This is indeed the case for quite a few settings. When checking the code i noticed we are using the dynamic loading feature and then returning an error when it's not in the Allowed List. That is not the intended usage of this functionality, the idea is to give the cors library one or more url's to validate against. If this needs to be pulled from an asynchronous source (a database for example) the dynamic loading feature can be used. The validation itself is done by the library.

https://expressjs.com/en/resources/middleware/cors.html#configuration-options

Solution: Just supply the library an array of url's and the error disappears
