### ISSUE TITLE
Server 2.1 fresh install - CanboatJS issue 

### ISSUE THREAD

**Issue by tkrofta** [SignalK/signalk-server#1594]
Fresh install for development purposes only (RPi3 - Raspberry OS bullseye latest updates with Node v18.17.0 - npm 9.8.1) 
receiving the following CanboatJS error with the sample N2K data set:

<Error: Cannot get 3 bit(s) from offset 200, 0 available
    at BitView.getBits (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/bit-buffer/bit-buffer.js:53:9)
    at BitStream.readBits (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/bit-buffer/bit-buffer.js:365:23)
    at readValue (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:702:16)
    at readField (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:577:13)
    at Parser._parse (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:207:21)
    at Parser.parseString (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:448:24)
    at Parser.parse (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:299:19)
    at CanboatJs._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/canboatjs.js:53:34)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Liner.ondata (node:internal/streams/readable:766:22)
    at Liner.emit (node:events:514:28)
    at Readable.read (node:internal/streams/readable:539:10)
    at flow (node:internal/streams/readable:1023:34)
Error: Cannot get 3 bit(s) from offset 264, 0 available
    at BitView.getBits (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/bit-buffer/bit-buffer.js:53:9)
    at BitStream.readBits (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/bit-buffer/bit-buffer.js:365:23)
    at readValue (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:702:16)
    at readField (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:577:13)
    at Parser._parse (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:207:21)
    at Parser.parseString (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:448:24)
    at Parser.parse (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:299:19)
    at CanboatJs._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/canboatjs.js:53:34)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Liner.ondata (node:internal/streams/readable:766:22)
    at Liner.emit (node:events:514:28)
    at Readable.read (node:internal/streams/readable:539:10)
    at flow (node:internal/streams/readable:1023:34)
Error: Cannot get 3 bit(s) from offset 264, 0 available
    at BitView.getBits (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/bit-buffer/bit-buffer.js:53:9)
    at BitStream.readBits (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/bit-buffer/bit-buffer.js:365:23)
    at readValue (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:702:16)
    at readField (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:577:13)
    at Parser._parse (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:207:21)
    at Parser.parseString (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:448:24)
    at Parser.parse (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/node_modules/@canboat/canboatjs/lib/fromPgn.js:299:19)
    at CanboatJs._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/canboatjs.js:53:34)
    at Transform._write (node:internal/streams/transform:175:8)
    at doWrite (node:internal/streams/writable:411:12)
    at clearBuffer (node:internal/streams/writable:572:7)
    at onwrite (node:internal/streams/writable:464:7)
    at Transform._read (node:internal/streams/transform:201:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at flow (node:internal/streams/readable:1023:34)
    at resume_ (node:internal/streams/readable:1004:3)

Anyone seeing similar issues or may know the root cause?

**Comment by sbender9** [comment]
I am seeing this too. Looking into it...

**Comment by sbender9** [comment]
The 129809 pgns in that test data are misinformed, they are not long enough. This is fixed in canboatjs 2.1 (which the sk server is not using yet).

Since this is not urgent, I do not plan to go back and fix 1.x canboatjs.

**Comment by tkrofta** [comment]
Thanks, that makes sense. Any way to get the server using a newer version of canboatjs as a workaround, resp. on an another note - is there a possibility to sample a data set from your own boat to be replayed as sample data?

**Comment by sbender9** [comment]
It's just ignoring that one pgn in the test data, so unless you really need that, you should be fine. 

You can turn on logging for your N2K connection on your boat, this would record log data in ~/.signalk.
