### ISSUE TITLE
SK 2.3.0 / Receiving intermittent TokenExpired: jwt errors 

### ISSUE THREAD

**Issue by naugehyde** [SignalK/signalk-server#1638]
Receiving intermittent TokenExpired: jwt errors in SK 2.3.0. when running UI. 
```
TokenExpiredError: jwt expired at /usr/lib/node_modules/signalk-server/node_modules/jsonwebtoken/verify.js:190:21 
      at getSecret (/usr/lib/node_modules/signalk-server/node_modules/jsonwebtoken/verify.js:97:14) 
      at module.exports [as verify] (/usr/lib/node_modules/signalk-server/node_modules/jsonwebtoken/verify.js:101:10) 
      at strategy.authorizeWS (/usr/lib/node_modules/signalk-server/lib/tokensecurity.js:576:27) 
      at strategy.verifyWS (/usr/lib/node_modules/signalk-server/lib/tokensecurity.js:535:22) 
      at FullSignalK.<anonymous> (/usr/lib/node_modules/signalk-server/lib/interfaces/ws.js:491:30) 
      at FullSignalK.emit (node:events:529:35) 
      at FullSignalK.addDelta (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:52:8) 
      at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:15:18) 
      at DeltaChain.process (/usr/lib/node_modules/signalk-server/lib/deltachain.js:11:21) 
      at Server.app.handleMessage (/usr/lib/node_modules/signalk-server/lib/index.js:223:38) 
      at Simple.<anonymous> (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:81:17) 
      at Simple.emit (node:events:529:35) 
      at addChunk (node:internal/streams/readable:335:12) 
      at readableAddChunk (node:internal/streams/readable:308:9) 
      at Readable.push (node:internal/streams/readable:245:10) { expiredAt: 2023-10-05T22:52:20.000Z }
```

**Comment by tkurki** [comment]
What devices are connecting to the server? Sounds like one is using an expired token and not acting on the failure, but blindly retrying.

**Comment by tkurki** [comment]
Closing as stale.
