### ISSUE TITLE
[DOCKER][BUG] SeaTalk GPIO integration not working

### ISSUE THREAD

**Issue by xGuIInE** [SignalK/signalk-server#1703]
Hello, 
I was integrating a SeaTalk module to my docker signalk server, and I faced with this issue.
The python script is executed using the `python -u -c '${cmd}' ${options.gpio} ${options.gpioInvert}`, but python is only aliased by python3, so it can't be loaded. 

[https://github.com/SignalK/signalk-server/blob/master/packages/streams/pigpio-seatalk.js](url) 

I fixed this using a custom Docker image:

```
FROM cr.signalk.io/signalk/signalk-server

USER root

RUN apt-get update
RUN apt-get install -y python3-pigpio
RUN apt-get install -y python-is-python3

USER node
```
python-is-python3 package does the trick.

**Comment by KEGustafsson** [comment]
Isn't this easiest to fix in pigpio-seatalk.js itself?
To add test which python is installed and then use it.

**Comment by xGuIInE** [comment]
Yes... this was a workaround/temporal solution.
I'm going to check if other modules use `python` call too and prepare a PR.

**Comment by xGuIInE** [comment]
@KEGustafsson after checking it further, `pigpio` package isn't installed in the docker image... throwing `ModuleNotFoundError: No module named 'pigpio'`
Docker base image should be updated, maybe keeping `python-is-python3` package is safer allowing to use both commands `python | python3`

**Comment by KEGustafsson** [comment]
You could add check which version of python is 7nstalled if required packages are installed too and if not then install with needed ones with pip. Once checked which python in use, then modify excutive part accordingly. To my understanding all changes can be done application level, no need to touch image.

**Comment by GraffJosh** [comment]
I find this same issue using GPIOD, but I can't seem to get permissions to work for gpiod running from Docker. After making a dockerfile similar to the above solution, I can get through to this error, where I am now stuck: 

`Aug 22 20:23:41 Traceback (most recent call last): File "<string>", line 32, in <module> File "/usr/local/lib/python3.12/dist-packages/gpiod/chip.py", line 64, in __init__ self._chip: Union[_ext.Chip, None] = _ext.Chip(path) ^^^^^^^^^^^^^^^ PermissionError: [Errno 13] Permission denied
Aug 22 20:23:41 2025-08-22T20:23:41.949Z @signalk/charts-plugin Chart plugin: Found 0 charts from /charts.
Aug 22 20:23:41 |python -u -c ' import gpiod, sys, datetime, glob ST_PIN ... [continues printing the entire seatalk function]`

I think the issue is just in the GPIOChip selection logic. If I run the seatalkTest python script inside the container, it also fails, but if I bypass the gpiochip selection logic and just force it to use gpiochip0, it works without error. 

For anyone else who finds this, I got this working on my system by making a _fake_ /proc/device-tree folder, and spoofing the model file with an invalid model name, forcing the python script to fallback to using ONLY gpioChip0. I use the docker-compose to point the container's /proc/device-tree to my fake folder, and voila: seatalk data. 

A bit of a hack, to be honest. It would be awesome if there were a canon docker-compose file. I have literally no idea how to make a change to signalk at that level, though, so I don't really know how to help. I may try for a PR to work on the selection code. 


My dockerfiles, if anyone finds this issue before it's closed. 

dockerfile:
```
FROM signalk/signalk-server:latest
USER root
# Install python3 and symlink "python" → "python3"

RUN apt-get update
RUN apt-get update && \
    apt-get install -y python3-pigpio python-is-python3 && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install gpiod --break-system-packages
USER node
```

docker-compose.yml:
```
services:
  signalk:
#    image: signalk/signalk-server:latest
    build:
      context: .
      dockerfile: gpiodockerfile
    container_name: signalk
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "10110:10110"
    devices:

      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiomem0:/dev/gpiomem0"
      - "/dev/gpiomem1:/dev/gpiomem1"
      - "/dev/gpiomem2:/dev/gpiomem2"
      - "/dev/gpiomem3:/dev/gpiomem3"
      - "/dev/mem:/dev/mem"
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - ./fakeProc/:/proc/device-tree:ro
      - ./signalk:/home/node/.signalk
      - /var/run/dbus:/var/run/dbus
    environment:
      - TZ=UTC
    privileged: true```
