### ISSUE TITLE
Tokensecurity error on reading properties

### ISSUE THREAD

**Issue by pa1pdr** [SignalK/signalk-server#1708]
On my windows 10 install SignalK v.2.6.2 I get the following error in the log:
```
TypeError: Cannot read properties of null (reading 'path') at c:\signalk\nodejs\node_modules\signalk-server\lib\tokensecurity.js:468:98 
at Array.find (<anonymous>) at c:\signalk\nodejs\node_modules\signalk-server\lib\tokensecurity.js:467:35 
at Array.find (<anonymous>) at strategy.shouldAllowWrite (c:\signalk\nodejs\node_modules\signalk-server\lib\tokensecurity.js:461:46) 
at processUpdates (c:\signalk\nodejs\node_modules\signalk-server\lib\interfaces\ws.js:366:31)
```

I've dropped all devices in 'Security', but that doesn't help. Reinstalled signalK: no dice.

**Comment by tkurki** [comment]
Disable security per https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions#how-to-disable-security-or-i-have-lost-my-admin-password-what-do-i-do and remove $HOME/.signalk/security.json and start over.

**Comment by tkurki** [comment]
Ah. I think something is creating invalid delta values with `null` in `values` array. No reconfiguration will fix the issue.

**Comment by tkurki** [comment]
Closing, as this is just an indication of broken input.

**Comment by pa1pdr** [comment]
> Ah. I think something is creating invalid delta values with `null` in `values` array. No reconfiguration will fix the issue.

I'll scrutinise my SensESP providers. So null is not acceptable as a value and will prevent that from being sent.

**Comment by tkurki** [comment]
https://discord.com/channels/1170433917761892493/1232349882858209421

**Comment by pa1pdr** [comment]
Sorry: my registration to discord fails.. Do you have any alternate means to communicate?

**Comment by tkurki** [comment]
I just added a pointer to a similar problem, did not mean to redirect this conversation there.
