### ISSUE TITLE
Different behaviours with canboat and canboatjs and signalk-n2kais-to-nmea0183

### ISSUE THREAD

**Issue by aviatorhh** [SignalK/signalk-server#1709]
My system is a RPI3 (Debian 12) with a vcan0 interface getting data via cannelloni and running Signal K Server version 2.6.2.
If I use canboatjs for a data connection the data comes in only for about one second and then stalls. During this first second AIS data is sent as NMEA0183 via port 10110 (signalk-n2kais-to-nmea0183).

If I switch the data connection to use canboat binaries all data comes in fine and continuously to SK but with the exception that no AIS data is sent via NMEA0813 then.

I cannot really distinguish if this is an issue with the plugin or the canboat implementation or SK. But as the plugin is capable of building NMEA0183 sentences I assume it is how SK uses the canboat(js) interfaces.

I am heading for canboat instead of canboatjs because according to github canboat seems to be more active.

**Comment by sbender9** [comment]
I'm not sure why canboatjs stops for you. It is used by most sk installs, including mine, and it never stops working. 

In general, canboatjs is less active because it is stable and the pgn definitions come from canboat and the canboatjs repository does even get updated when those change. 

The n2kais plugin should work with canboat, I can look into that. 

I would be very interested in why canboatjs stops working for you. I have seen this before and it was resolved by the user, sadly I don't remember what fixed it and the record of that conversation is gone...

**Comment by tkurki** [comment]
Do you see anything notable, like errors,  in server log when canboatjs stops?

**Comment by aviatorhh** [comment]
Apr 02 22:30:49 signalk-server running at 0.0.0.0:[object Object]Apr 02 22:30:49 [object Object]That is all I can find at the moment that might look strangeOn 2. Apr 2024, at 21:25, Teppo Kurki ***@***.***> wrote:﻿
Do you see anything notable, like errors,  in server log when canboatjs stops?

**Comment by aviatorhh** [comment]
Apr 02 22:30:49 signalk-server running at 0.0.0.0:[object Object]
Apr 02 22:30:49 [object Object]

That is all I can find that looks strange but I assume it has nothing todo with it.
Can I run SK in a debug mode and tail on a logfile?

**Comment by sbender9** [comment]
On the n2kais plugin issue. Do you actually see any AIS data in the Data Browser when using canboat?

**Comment by aviatorhh** [comment]
> On the n2kais plugin issue. Do you actually see any AIS data in the Data Browser when using canboat?

Yes AIS and paths are fine but are not dumped out of the plugin.

**Comment by aviatorhh** [comment]
> can you try this:
> 
> ```
> sudo npm install -g @canboat/canboatjs
> candumpjs vecan0
> ```
> 
> This will just dump everything from vecan0 using canboatjs. Hopefully we'll see an error there...

Runs flawlessly

**Comment by aviatorhh** [comment]
Found something 


Apr 02 23:00:50 TypeError: Cannot read properties of undefined (reading 'toString') at N2kMapper.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/n2k-signalk.js:57:26) at N2kMapper.emit (node:events:517:28) at N2kMapper.toDelta (/usr/lib/node_modules/signalk-server/node_modules/@signalk/n2k-signalk/n2kMapper.js:149:14) at ToSignalK._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/n2k-signalk.js:113:34) at Transform._write (node:internal/streams/transform:175:8) at writeOrBuffer (node:internal/streams/writable:392:12) at _write (node:internal/streams/writable:333:10) at Writable.write (node:internal/streams/writable:337:10) at N2KAnalyzer.ondata (node:internal/streams/readable:809:22) at N2KAnalyzer.emit (node:events:517:28) at addChunk (node:internal/streams/readable:368:12) at readableAddChunk (node:internal/streams/readable:341:9) at Readable.push (node:internal/streams/readable:278:10) at Interface.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/n2kAnalyzer.js:52:12) at Interface.emit (node:events:517:28) at [_onLine] [as _onLine] (node:internal/readline/interface:423:12)
Apr 02 23:00:50 [object Object]


canboat bin

**Comment by sbender9** [comment]
That's with canboatjs?

That stack trace does not make sense to me... @tkurki ?

**Comment by aviatorhh** [comment]
No, as written below canboat bin

**Comment by aviatorhh** [comment]
At which point in the SK code you get the stream out of the canboat bin version into the parser?
I found n2k-signalk but could not determine the stdin entry point.

**Comment by tkurki** [comment]
Not stdin but Node streams, see https://github.com/SignalK/signalk-server/tree/master/packages/streams

**Comment by aviatorhh** [comment]
Some more Info. If I select the canboat bin the N2KAnalyzerOut event disappears after restart. That is why the AIS plugin is never called. The event is not shown as a selectable option within the server log list either.
I guess somewhere at startup there seems to be a break (stack trace from above?) that prevents that event from being created.

**Comment by aviatorhh** [comment]
Maybe it has to do with the raw n2k can messages?
I am running a SK instance on a different machine that streams out the paths over the canbus (n2k) which then is being catched by the system I am having these issues. Maybe there is some data missing while doing paths-to-n2k on the other server?
