### ISSUE TITLE
Type Error in Systemctl Status

### ISSUE THREAD

**Issue by yachtwave** [SignalK/signalk-server#1716]
Getting "TypeError: Cannot read properties of undefined (reading 'ws')" Is there somethign I can do to resolve it?

Apr 09 23:23:01 yachtwave-signalk signalk-server[548]:     at listOnTimeout (node:internal/timers:569:17)
Apr 09 23:23:01 yachtwave-signalk signalk-server[548]:     at process.processTimers (node:internal/timers:512:7)
Apr 09 23:23:06 yachtwave-signalk signalk-server[548]: TypeError: Cannot read properties of undefined (reading 'ws')
Apr 09 23:23:06 yachtwave-signalk signalk-server[548]:     at Timeout._onTimeout (/usr/local/lib/node_modules/signalk-server/lib/deltastats.js:56:46)
Apr 09 23:23:06 yachtwave-signalk signalk-server[548]:     at listOnTimeout (node:internal/timers:569:17)
Apr 09 23:23:06 yachtwave-signalk signalk-server[548]:     at process.processTimers (node:internal/timers:512:7)
Apr 09 23:23:11 yachtwave-signalk signalk-server[548]: TypeError: Cannot read properties of undefined (reading 'ws')
Apr 09 23:23:11 yachtwave-signalk signalk-server[548]:     at Timeout._onTimeout (/usr/local/lib/node_modules/signalk-server/lib/deltastats.js:56:46)
Apr 09 23:23:11 yachtwave-signalk signalk-server[548]:     at listOnTimeout (node:internal/timers:569:17)

**Comment by tkurki** [comment]
Never seen this before. What is your Node version?

**Comment by tkurki** [comment]
No feedback, closing.

**Comment by swork** [comment]
I have same sequence of errors on a new install, node version 18.19.0, rpi4, OS 6.6.31+rpt-rpi-v8.

**Comment by tkurki** [comment]
Please describe your system: what connections and inputs do you have? Active plugins?

Can you include the error messages also.

**Comment by swork** [comment]
Bare rpi4 with no IO connections. apt package nodejs just installed. npm install -g signalk-server, then sudo signalk-server-setup:

manage_sensors@bighat:~ $ sudo signalk-server-setup
  ____    _                           _     _  __
 / ___|  (_)   __ _   _ __     __ _  | |   | |/ /
 \___ \  | |  / _` | | '_ \   / _` | | |   | ' /
  ___) | | | | (_| | | | | | | (_| | | |   | . \
 |____/  |_|  \__, | |_| |_|  \__,_| |_|   |_|\_\
              |___/

YOU ARE LOGGED IN AS manage_sensors AND THE SERVER WILL BE STARTED AS THIS USER

? Enter the location to store server configuration: /home/manage_sensors/.signal
k
? Enter your vessel name: WN6768NN
? Enter your mmsi if you have one:

The Signal K default port is 3000
Port 80 does not require ":3000" in the browser and app interfaces

? Do you want to use port 80? No
? Do you want to enable SSL? Yes
  ✔ Creating your server base deltas at /home/manage_sensors/.signalk/baseDeltas
.json
  ✔ Creating your server settings at /home/manage_sensors/.signalk/settings.json
  ✔ Creating package.json
  ✔ Creating your server startup script at /home/manage_sensors/.signalk/signalk
-server
  ✔ Updating file ownership and permissions
  ✔ Setting up your server to start Signal K when booting up
  ✔ Running 'systemctl daemon-reload'
  ✔ Running 'systemctl enable signalk.service'
  ✔ Running 'systemctl enable signalk.socket'
  ✔ Running 'systemctl stop signalk.service'
  ✔ Running 'systemctl restart signalk.socket'
  ✔ Running 'systemctl restart signalk.service'
manage_sensors@bighat:~ $ ps ax|grep signal
   7671 ?        Ss     0:00 /bin/sh /home/manage_sensors/.signalk/signalk-server
   7672 ?        Sl     0:10 node /usr/local/lib/node_modules/signalk-server/bin/signalk-server -c /home/manage_sensors/.signalk
   7742 pts/1    S+     0:00 grep --color=auto signal

Connections to :3000 hung indefinitely, and this appeared in 'journalctl -xe' output:

Jun 26 13:30:21 bighat signalk-server[7672]: TypeError: Cannot read properties of undefined (reading 'ws')
Jun 26 13:30:21 bighat signalk-server[7672]:     at Timeout._onTimeout (/usr/local/lib/node_modules/signalk-server/lib/deltastats.js:56:46)
Jun 26 13:30:21 bighat signalk-server[7672]:     at listOnTimeout (node:internal/timers:569:17)
Jun 26 13:30:21 bighat signalk-server[7672]:     at process.processTimers (node:internal/timers:512:7)
Jun 26 13:30:26 bighat signalk-server[7672]: TypeError: Cannot read properties of undefined (reading 'ws')
Jun 26 13:30:26 bighat signalk-server[7672]:     at Timeout._onTimeout (/usr/local/lib/node_modules/signalk-server/lib/deltastats.js:56:46)
Jun 26 13:30:26 bighat signalk-server[7672]:     at listOnTimeout (node:internal/timers:569:17)
Jun 26 13:30:26 bighat signalk-server[7672]:     at process.processTimers (node:internal/timers:512:7)

(repeating at 5s intervals).

Repeating "sudo signalk-server-setup" answering No to SSL eliminated the problem, the server appears to work as expected given no configuration.

**Comment by dirkwa** [comment]
The code in `deltastats.ts` that caused this crash has been fixed in v2.x (commit e3c2c9be, August 2024). The `app.interfaces.ws` access is now guarded so the stats timer no longer throws if the WebSocket interface hasn't initialized yet.

The original reports were both from early/mid 2024 on older server versions. @swork — if you're still experiencing this on a current version (2.23.x), please let us know. Otherwise, can this issue be closed?
