### ISSUE TITLE
app.getFeatures broken

### ISSUE THREAD

**Issue by VladimirKalachikhin** [SignalK/signalk-server#1777]
Signal K Server  version 2.8.3

The server plugin function [app.getFeatures](https://github.com/SignalK/signalk-server/blob/master/docs/src/develop/plugins/server_plugin_api.md#appgetfeaturesenabed) does not work.
Code:
```
plugin.start = function (options, restartPlugin) {
  let features = app.getFeatures();
};
```
Result:
```
TypeError: app.getPluginsList is not a function
    at Server.<anonymous> (/usr/local/lib/node_modules/signalk-server/lib/index.js:94:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/signalk-server/lib/index.js:26:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/signalk-server/lib/index.js:22:12)
    at Object.Server.app.getFeatures (/usr/local/lib/node_modules/signalk-server/lib/index.js:91:40)
    at Object.plugin.start (/home/stager/projects/webNav/signalk/galadrielcacheskcharts/index.js:29:20)
    at doPluginStart (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:305:20)
    at doRegisterPlugin (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:459:13)
    at registerPlugin (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:258:13)
    at /usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:209:13
    at Array.forEach (<anonymous>)
    at startPlugins (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:208:85)
    at Object.start (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:46:13)
    at /usr/local/lib/node_modules/signalk-server/lib/index.js:503:50
    at /usr/local/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:4967:15
    at Function.forIn (/usr/local/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:13018:11)
    at startInterfaces (/usr/local/lib/node_modules/signalk-server/lib/index.js:480:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/signalk-server/lib/index.js:328:17)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/signalk-server/lib/index.js:23:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by tkurki** [comment]
@panaaj any ideas?

**Comment by panaaj** [comment]
The issue is due to running `getFeatures()` in the start up function.....
You cannot get a list of plugins because the plugin manager has not finished untill all plugins are started, so asking for the list of plugins synchronously during plugin startup is an issue.
Waiting until all plugins are loaded (pluginManager is complete) solves the issue...
e.g. using `setTimeout( async () => console.log(await server.getFeatures(), 1000))` in plugin startup code completes successfully.

**Comment by VladimirKalachikhin** [comment]
A real workaround is:
```
setImmediate(()=>app.getFeatures());
```
but it's pointless.

The real code could be
```
setImmediate(() => {let features = app.getFeatures();});
```
but!:
```
setImmediate(()=>{let features = app.getFeatures(); app.debug(features instanceof Promise)});
```
In fact .getFeatures() return Promise when as the documentation says 
"Returns an object detailing the available APIs and Plugins."

OK,  if the .getFeatures() returns Promise instead result, then the code should be:
```
app.getFeatures().then((features)=>{app.debug('features list:',features)});
```
but it's get 
**TypeError: app.getPluginsList is not a function**
That is the problem.

So a real real workaround is:
```
setImmediate(() => {app.getFeatures().then((features)=>{app.debug('features list:',features)});});
```
That is, to start the asynchronous function only on the next turn of the main cycle.
It seems to me that this is nonsense.

**Comment by tkurki** [comment]
This is kinda tricky: plugin A provides feature 1 if there is feature 2 available and feature 2 is provided by plugin B, that needs to be started. Somewhat similar to systemd dependencies with `requires` and `wants`.

We have already a similar method for plugins to "announce" properties:
- emit: https://github.com/SignalK/nmea0183-signalk/blob/master/custom-sentence-plugin/index.js#L15
- listen: https://github.com/SignalK/nmea0183-signalk/blob/6c3351c0b28ac943517a95fe076d87c4c661cf01/lib/index.js#L46

The difference to regular events is that listeners get all the emitted values, not just future values. A poor man's event broker with retain = true, if you will.

We could change the feature detection api to use app properties API, forcing plugins to react to features coming available.

This would also cover the case where a plugin providing a feature is activated later, after server startup.

**Comment by dirkwa** [comment]
This was fixed in commit 17222a43 (shipped in v2.15.0). The issue was that `startPlugins()` was called before `app.getPluginsList` was assigned, so any plugin calling `app.getFeatures()` during `start()` would fail. The initialization order is now correct — `getPluginsList` is assigned before plugins start.

@VladimirKalachikhin can you confirm this works on v2.15+ so we can close this?

**Comment by VladimirKalachikhin** [comment]
> [@VladimirKalachikhin](https://github.com/VladimirKalachikhin) can you confirm this works on v2.15+ so we can close this?

I did not try version 2.15+ because it requires a node.js version that is not in my repository.

**Comment by dirkwa** [comment]
Sad to hear this. Maybe you can back port it when it's important for you. I don't think anyone else would do it for this outdated version.

May I ask you to close this case? 

Thanks.

**Comment by VladimirKalachikhin** [comment]
Perhaps, when the riot of interfaces calms down, I will bring my applications in line with the established API.
