### ISSUE TITLE
app.notify not working

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1795]
Just updated to server version 2.11.0.

I have a plugin which makes a simple call:
```
app.notify(watchdog.notificationPath, { state: 'alert', message: 'Waiting for interface to become active' }, plugin.id)
```
(the notification path and plugin id are valid string values).

The call fails with:
```
error starting plugin: Error: Route.notify() requires a callback function but got a [object Object]
Error: Route.notify() requires a callback function but got a [object Object]
    at Route.<computed> [as notify] (/opt/homebrew/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:216:15)
    at app.<computed> [as notify] (/opt/homebrew/lib/node_modules/signalk-server/node_modules/express/lib/application.js:499:19)
    at /Users/preeve/.signalk/node_modules/pdjr-skplugin-interfacewatchdog/dist/index.js:145:25
    at Array.forEach (<anonymous>)
    at Object.start (/Users/preeve/.signalk/node_modules/pdjr-skplugin-interfacewatchdog/dist/index.js:142:42)
    at doPluginStart (/opt/homebrew/lib/node_modules/signalk-server/lib/interfaces/plugins.js:305:20)
    at doRegisterPlugin (/opt/homebrew/lib/node_modules/signalk-server/lib/interfaces/plugins.js:459:13)
    at registerPlugin (/opt/homebrew/lib/node_modules/signalk-server/lib/interfaces/plugins.js:258:13)
    at /opt/homebrew/lib/node_modules/signalk-server/lib/interfaces/plugins.js:209:13
    at Array.forEach (<anonymous>)
    at startPlugins (/opt/homebrew/lib/node_modules/signalk-server/lib/interfaces/plugins.js:208:85)
    at Object.start (/opt/homebrew/lib/node_modules/signalk-server/lib/interfaces/plugins.js:46:13)
    at /opt/homebrew/lib/node_modules/signalk-server/lib/index.js:503:50
    at /opt/homebrew/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:4967:15
    at Function.forIn (/opt/homebrew/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:13018:11)
    at startInterfaces (/opt/homebrew/lib/node_modules/signalk-server/lib/index.js:480:22)
```

**Comment by tkurki** [comment]
@panaaj [documentation](https://github.com/SignalK/signalk-server/blob/master/docs/src/develop/plugins/server_plugin_api.md?plain=1#L657-L698) for app.notify was added in fc9e64d0c1e0bb7b65b8dacbeac7f0c995239980 but where is it implemented?

**Comment by tkurki** [comment]
The error message is coming from [Express routing method](https://expressjs.com/en/4x/api.html#routing-methods).

**Comment by panaaj** [comment]
> @panaaj [documentation](https://github.com/SignalK/signalk-server/blob/master/docs/src/develop/plugins/server_plugin_api.md?plain=1#L657-L698) for app.notify was added in [fc9e64d](https://github.com/SignalK/signalk-server/commit/fc9e64d0c1e0bb7b65b8dacbeac7f0c995239980) but where is it implemented?

This has somehow snuck through from #1560. I will raise a PR to remove it.

**Comment by preeve9534** [comment]
Just raising a (maybe premature) flag here, but the title of #1796 is rather misleading. AFAIK app.notify has been available and working in SK for a long time. Some recent change in the code base has broken it - this isn't just a documentation issue.

**Comment by tkurki** [comment]
`app.notify` did not ring any bells in my head, then I found the reference in the documentation, but no trace of an implementation.

Just fired off a few tests with 2.5.0 and 2.0.0, they both throw the same error. I think you're mistaken.

**Comment by preeve9534** [comment]
@tkurki - yes you are correct - sorry for the confusion.

It seems that at some point in the distant past I created a wrapper for app that implemented the server API elements that were documented but not yet implemented and amongst these was app.notify().  Move forward five years or so and I awrote this wrapper out of use when I was recoding things into Typescript and wondered why my plugin was causing Signal K to throw an error when app.notify() was documented. Wish I had a perfect memory! My bad.

**Comment by tkurki** [comment]
No worries!
