### ISSUE TITLE
constant error every second in the log

### ISSUE THREAD

**Issue by seamaster101** [SignalK/signalk-server#1848]
Hi 
I'm getting this in the log. I have no idea how to fix. Can you please help?

`Error: Error: position is not valid at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:687:27) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.setDestination (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:643:16) at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:179:43) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.parseStreamValue (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:172:16) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:152:34 at Array.forEach (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:148:35 at Array.forEach (<anonymous>)
Dec 16 09:59:06 Error: Error: position is not valid at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:687:27) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.setDestination (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:643:16) at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:179:43) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.parseStreamValue (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:172:16) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:152:34 at Array.forEach (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:148:35 at Array.forEach (<anonymous>)
Dec 16 09:59:07 Error: Error: position is not valid at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:687:27) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.setDestination (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:643:16) at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:179:43) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.parseStreamValue (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:172:16) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:152:34 at Array.forEach (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:148:35 at Array.forEach (<anonymous>)
Dec 16 09:59:08 Error: Error: position is not valid at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:687:27) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.setDestination (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:643:16) at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:179:43) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.parseStreamValue (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:172:16) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:152:34 at Array.forEach (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:148:35 at Array.forEach (<anonymous>)
Dec 16 09:59:08 Error: Error: position is not valid at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:687:27) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.setDestination (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:643:16) at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:179:43) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.parseStreamValue (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:172:16) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:152:34 at Array.forEach (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:148:35 at Array.forEach (<anonymous>)
 `

**Comment by panaaj** [comment]
This is due to invalid position information being received. See https://github.com/SignalK/signalk-server/pull/1840

**Comment by tkurki** [comment]
A duplicate of #1845 . There's a fix, but it is not published yet.

You can filter out bad values with the Node-RED plugin if you need to get rid of this sooner.
